apiName: "WebShopAPI"

assets:
  mappings:
    /assets: /pictures
  overrides:
    /pictures: pictures

server:
  rootPath: /api/*
  applicationConnectors:
   - type: http
     port: 8080
   - type: https
     port: 8443
     keyStorePath: WebShop.keystore
     keyStorePassword: crimson

