apiName: "WebShopAPI"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../WebShopClient/

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
   - type: http
     port: 8080
  adminConnectors:
   - type: http
     port: 8081
